# Site settings
title: Sam Morris
email: mail@sammorrisdesign.co.uk
description: "The portfolio of Sam Morris. A mobile and web designer currently working at The Guardian."
baseurl: ""
url: "http://www.sammorr.is"

# Build settings
markdown: kramdown
permalink: pretty