# Site settings
title: Sam Morris
email: mail@sammorrisdesign.co.uk
description: "The portfolio of Sam Morris. A mobile and web designer currently working at The Guardian in New York."
short-description: "Mobile & Web Designer"
baseurl: ""
url:  "http://sammorr.is"

# Build settings
permalink: pretty